source 'https://rubygems.org'

gem 'ap'
gem 'awesome_print'
gem 'capistrano'
gem 'crack'
gem 'dalli'
gem 'factory_girl', '4.1.0'
gem 'faker', '0.9.5'
gem 'formtastic'
gem 'googlecharts', '1.6.8', require: 'gchart'
gem 'haml-rails'
gem 'headless'
gem 'jquery-rails'
gem 'money'
gem 'nokogiri'
gem 'pg'
gem 'pry'
gem 'rails', '3.2.11'
gem 'sqlite3'
gem 'watir-webdriver'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'uglifier', '>= 1.0.3'
end
